### ISSUE TITLE
[Question] How to change the refresh speed?

### ISSUE THREAD

**Issue by WorldOfFunYT** [DataGraph1/MC-Live-Wallpaper#1]
I wanted to make the wallpaper change more often, like twice as fast, how do I do that?

**Comment by DataGraph1** [comment]
I'm currently working on improving usability and as a few people have requested this feature I'll try to make a much easier and quicker way to change the refresh speed soon.

However if you want to incress refresh speed now, you can change it by multiplying the number of screenshots and "framesForTime" values in the "timesList.json" file. 
E.g. to make it go 2 times as quickly take a screenshot every 0.6 seconds, instead 1.2s (totalling 2880 images, instead of 1440) and change the values in "timesList.json" > "framesForTime" to be [160, 1280, 160, 1320, 1320]
I've tested it out and it seems to work perfectly

**Comment by WorldOfFunYT** [comment]
Thanks!
